openapi: 3.0.3
info:
  title: Docusaurus Chatbot API
  description: API for the embedded chatbot in the Docusaurus book frontend that communicates with the RAG backend agent
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server
paths:
  /query:
    post:
      summary: Submit a query to the RAG agent
      description: Accepts a user question and optional selected text context, returns relevant answers from the book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response with relevant content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Bad request - invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's question
          example: "What are the key concepts in robotics?"
        selected_text:
          type: string
          description: Text selected on the current page (for context-specific queries)
          example: "Robotics is an interdisciplinary field..."
        context:
          type: object
          description: Information about the current page context
          properties:
            page_url:
              type: string
              description: Current page URL
              example: "https://example.com/book/chapter1"
            page_title:
              type: string
              description: Current page title
              example: "Introduction to Robotics"
            section:
              type: string
              description: Current section name
              example: "Chapter 1.1"
        top_k:
          type: integer
          description: Number of results to return (default: 5)
          example: 5
          minimum: 1
          maximum: 20
          default: 5
    QueryResponse:
      type: object
      required:
        - response_id
        - query_id
        - status
      properties:
        response_id:
          type: string
          description: Unique identifier for the response
          example: "resp_12345"
        query_id:
          type: string
          description: Reference to the original query
          example: "query_67890"
        answer_text:
          type: string
          description: The main answer text from the RAG system
          example: "Robotics is an interdisciplinary field that includes mechanical engineering, electrical engineering, and computer science..."
        source_chunks:
          type: array
          description: Array of content chunks that support the answer
          items:
            $ref: '#/components/schemas/SourceChunk'
        status:
          type: string
          description: Status of the response
          enum: [success, error, empty]
          example: "success"
        timestamp:
          type: string
          format: date-time
          description: When the response was generated
          example: "2025-12-17T10:30:00Z"
    SourceChunk:
      type: object
      properties:
        chunk_id:
          type: string
          description: Unique identifier for the content chunk
          example: "chunk_67890"
        text:
          type: string
          description: The actual content text from the source
          example: "Robotics is an interdisciplinary field that includes mechanical engineering, electrical engineering, and computer science..."
        url:
          type: string
          description: URL of the source page
          example: "https://example.com/book/chapter1"
        page_title:
          type: string
          description: Title of the source page
          example: "Introduction to Robotics"
        section:
          type: string
          description: Section name in the source document
          example: "Chapter 1.1"
        chunk_index:
          type: integer
          description: Index position of this chunk in the original content
          example: 1
        source_url:
          type: string
          description: URL of the original source
          example: "https://example.com/book"
        chunk_hash:
          type: string
          description: Hash of the content for deduplication
          example: "a1b2c3d4e5f6"
        score:
          type: number
          format: float
          description: Relevance score from RAG system
          example: 0.95
    ErrorResponse:
      type: object
      required:
        - response_id
        - status
        - error_message
      properties:
        response_id:
          type: string
          description: Unique identifier for the response
          example: "resp_12345"
        query_id:
          type: string
          description: Reference to the original query (if available)
          example: "query_67890"
        status:
          type: string
          description: Status of the response
          enum: [error]
          example: "error"
        error_message:
          type: string
          description: User-friendly error message
          example: "Unable to process query at this time"
        error_code:
          type: string
          description: Technical error code
          example: "INTERNAL_ERROR"
        timestamp:
          type: string
          format: date-time
          description: When the error occurred
          example: "2025-12-17T10:30:00Z"