<?xml version="1.0"?>
<robot name="modular_torso_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.14159265359"/>
  <xacro:property name="arm_length" value="0.3"/>
  <xacro:property name="arm_mass" value="0.75"/>
  <xacro:property name="shoulder_offset_y" value="0.15"/>
  <xacro:property name="shoulder_pos_z" value="0.4"/>

  <link name="torso">
    <visual>
      <geometry><box size="0.2 0.3 0.6"/></geometry>
      <material name="Grey"><color rgba="0.7 0.7 0.7 1"/></material>
    </visual>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.05"/>
    </inertial>
  </link>

  <xacro:macro name="arm_segment" params="prefix parent_link axis_xyz joint_xyz">
    
    <joint name="${prefix}_joint" type="revolute">
      <parent link="${parent_link}"/>
      <child link="${prefix}_link"/>
      <origin xyz="${joint_xyz}" rpy="0 0 0"/>
      <axis xyz="${axis_xyz}"/>
      <limit effort="5" velocity="0.5" lower="-${PI/2}" upper="${PI/2}"/>
    </joint>

    <link name="${prefix}_link">
      <visual>
        <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="0.05" length="${arm_length}"/></geometry>
        <material name="Blue"><color rgba="0 0 1 1"/></material>
      </visual>
      <inertial>
        <mass value="${arm_mass}"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
    
  </xacro:macro>

  <xacro:arm_segment 
    prefix="right_shoulder" 
    parent_link="torso" 
    axis_xyz="1 0 0" 
    joint_xyz="0 -${shoulder_offset_y} ${shoulder_pos_z}"/>

  <xacro:arm_segment 
    prefix="left_shoulder" 
    parent_link="torso" 
    axis_xyz="1 0 0" 
    joint_xyz="0 ${shoulder_offset_y} ${shoulder_pos_z}"/>

</robot>