openapi: 3.0.3
info:
  title: RAG Agent API
  description: API for the RAG (Retrieval-Augmented Generation) agent that queries Qdrant embeddings and returns relevant book content
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-12-17T10:30:00Z"
  /query:
    post:
      summary: Query the RAG agent
      description: Accepts a user question and returns relevant book content chunks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The user's question
                  example: "What are the key concepts in robotics?"
                top_k:
                  type: integer
                  description: Number of results to return (default: 5)
                  example: 5
                  minimum: 1
                  maximum: 20
                  default: 5
      responses:
        '200':
          description: Successful response with relevant content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Bad request - invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /logs:
    get:
      summary: Get query logs
      description: Retrieve logs of processed queries (for monitoring purposes)
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: Number of log entries to return
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [success, error]
          description: Filter logs by status
      responses:
        '200':
          description: List of query logs
          content:
            application/json:
              schema:
                type: object
                properties:
                  logs:
                    type: array
                    items:
                      $ref: '#/components/schemas/QueryLog'
                  total:
                    type: integer
components:
  schemas:
    QueryResponse:
      type: object
      properties:
        query_id:
          type: string
          description: Unique identifier for the query
          example: "query_12345"
        results:
          type: array
          items:
            $ref: '#/components/schemas/ContentChunk'
        total_results:
          type: integer
          description: Total number of results returned
          example: 3
        processing_time:
          type: number
          format: float
          description: Time taken to process the query in milliseconds
          example: 123.45
        status:
          type: string
          description: Status of the request
          enum: [success, error]
          example: "success"
    ContentChunk:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the chunk
          example: "chunk_67890"
        text:
          type: string
          description: The actual content text
          example: "Robotics is an interdisciplinary field that includes mechanical engineering, electrical engineering, and computer science..."
        url:
          type: string
          description: URL of the source page
          example: "https://example.com/book/chapter1"
        page_title:
          type: string
          description: Title of the source page
          example: "Introduction to Robotics"
        section:
          type: string
          description: Section name in the source document
          example: "Chapter 1.1"
        chunk_index:
          type: integer
          description: Index position of this chunk in the original content
          example: 1
        source_url:
          type: string
          description: URL of the original source
          example: "https://example.com/book"
        chunk_hash:
          type: string
          description: Hash of the content for deduplication
          example: "a1b2c3d4e5f6"
        score:
          type: number
          format: float
          description: Relevance score from Qdrant search
          example: 0.95
    ErrorResponse:
      type: object
      properties:
        query_id:
          type: string
          description: Unique identifier for the query (if available)
          example: "query_12345"
        status:
          type: string
          description: Status of the request
          enum: [error]
          example: "error"
        error_message:
          type: string
          description: Description of the error
          example: "Invalid query format"
        processing_time:
          type: number
          format: float
          description: Time taken before error occurred in milliseconds
          example: 10.23
    QueryLog:
      type: object
      properties:
        log_id:
          type: string
          description: Unique identifier for the log entry
          example: "log_111222"
        query_text:
          type: string
          description: The original query text
          example: "What are the key concepts in robotics?"
        response_summary:
          type: string
          description: Brief summary of the response
          example: "3 content chunks returned"
        processing_time:
          type: number
          format: float
          description: Time taken to process in milliseconds
          example: 123.45
        timestamp:
          type: string
          format: date-time
          description: When the query was processed
          example: "2025-12-17T10:30:00Z"
        status:
          type: string
          description: Status of processing
          enum: [success, error]
          example: "success"
        error_details:
          type: string
          description: Details if an error occurred
          example: "Connection timeout to Qdrant"